version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017" # Map container's 27017 to host's 27018
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  client:
    build:
      context: ./client  # Path to your client app directory (e.g., Vite or React)
      dockerfile: Dockerfile  # Adjust if your Dockerfile is named differently
    ports:
      - "5173:5173"  # Map container's port to host's port for client (Vite)
    depends_on:
      - app  # Ensure the server is available before the client starts
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
